"""Second

Revision ID: a03cfd542b41
Revises: 25d49da4844b
Create Date: 2022-06-15 17:46:36.269048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a03cfd542b41'
down_revision = '25d49da4844b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
